services:
  node:
    image: 'node:20'
    container_name: six-cities-node
    user: 'node'
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/node/app
    ports:
      - 127.0.0.1:3123:3123
      - 127.0.0.1:5000:${PORT}

  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - six-cities_data:/data/db

  db_ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@db:${DB_PORT}/

volumes:
  six-cities_data:
